import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { S3Client, HeadBucketCommand } from '@aws-sdk/client-s3';
import type { EnvConfig } from '../common/config/env.validation.js';

/**
 * R2Client — wraps the AWS SDK S3Client configured for Cloudflare R2.
 *
 * Cloudflare R2 exposes an S3-compatible API at:
 *   https://<account-id>.r2.cloudflarestorage.com
 *
 * Key rules:
 *   - Bucket is PRIVATE — no public URLs, no CORS that allows direct browser access
 *   - All file access must go through signed URLs generated by the backend
 *   - Object keys must be UUID-based — never include names or personal data
 *
 * On startup: a lightweight HeadBucket check is performed to validate credentials.
 * A failed check logs a warning and continues — the app must not crash on storage
 * unavailability (degraded mode, not fatal).
 */
@Injectable()
export class R2Client implements OnModuleInit {
  private readonly logger = new Logger(R2Client.name);
  readonly client: S3Client;
  readonly bucketName: string;

  constructor(private readonly configService: ConfigService<EnvConfig, true>) {
    const endpoint = this.configService.get('R2_ENDPOINT', { infer: true });
    const accessKeyId = this.configService.get('R2_ACCESS_KEY_ID', {
      infer: true,
    });
    const secretAccessKey = this.configService.get('R2_SECRET_ACCESS_KEY', {
      infer: true,
    });
    this.bucketName =
      this.configService.get('R2_BUCKET_NAME', { infer: true }) ?? '';

    this.client = new S3Client({
      region: 'auto', // R2 does not use AWS regions — 'auto' is the correct value
      endpoint: endpoint ?? undefined,
      credentials:
        accessKeyId && secretAccessKey
          ? { accessKeyId, secretAccessKey }
          : undefined,
      // Force path-style URLs for R2 compatibility (virtual-hosted style is not supported)
      forcePathStyle: false,
    });
  }

  /**
   * Verifies R2 connectivity on module startup.
   *
   * Uses HeadBucket (no data transfer) to confirm credentials and bucket exist.
   * Logs a warning on failure — does NOT crash the app.
   */
  async onModuleInit(): Promise<void> {
    if (!this.bucketName) {
      this.logger.warn(
        '[R2Client] R2_BUCKET_NAME non configuré — stockage R2 désactivé.',
      );
      return;
    }

    try {
      await this.client.send(
        new HeadBucketCommand({ Bucket: this.bucketName }),
      );
      this.logger.log(
        `[R2Client] Connexion au bucket R2 "${this.bucketName}" établie.`,
      );
    } catch (err: unknown) {
      // Storage being unreachable must not prevent the app from starting.
      // Upload/download endpoints will fail gracefully at request time.
      this.logger.warn(
        `[R2Client] Impossible de vérifier le bucket R2 "${this.bucketName}": ${String(err)}. ` +
          `L'application démarre en mode dégradé — le stockage peut ne pas fonctionner.`,
      );
    }
  }
}
